[workspace]
members = ["collections","enums", "errors", "generics","guessing_game", "lifetimes", "my-project", "ownership", "restaurant", "structs", "traits", "variables"]
resolver = "2"

[package]
name = "rust-tryout"
version = "0.1.0"
edition = "2024"

[dependencies]
