[workspace]
members = ["collections","enums", "errors","guessing_game", "my-project", "ownership", "restaurant", "structs", "variables"]
resolver = "2"

[package]
name = "rust-tryout"
version = "0.1.0"
edition = "2024"

[dependencies]
